/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe for compose healthchecks and deploy smoke */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP (S1 → S2)
         * @description Validates the invite code and sends a one-time code to the email.
         *     Rate-limited; resend cooldown is a contract constant
         *     (`OTP_RESEND_COOLDOWN_S = 60`).
         */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify OTP (S2 → S3 or straight to S4 for existing users) */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete profile setup (S3 → S4)
         * @description Sets the display name and binds the immutable unique tag
         *     `name#NNNN`. Requires `needsProfile` session. If the requested tag
         *     prefix is taken, `tagSuggestions` are returned instead. One-shot:
         *     on an account that already has a profile this returns
         *     `conflict` — use `PATCH /users/me` for later display-name changes
         *     (the tag never changes). When `requestedTag` is omitted the
         *     display-name prefix is attempted; a collision also yields
         *     `tag_taken` + suggestions.
         */
        post: operations["completeProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate access + refresh tokens
         * @description Refresh tokens rotate on every use — the presented token is
         *     invalidated and a new pair is issued. Presenting an already-used
         *     refresh token (reuse detected, possible theft) revokes the entire
         *     device session: client gets `unauthorized` and must log in again.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current device session
         * @description Revokes this device's session; Web Push subscriptions bound to it
         *     are removed with it.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List device sessions (S14) */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a specific device session (S14) */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own profile (app cold start, S4) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own profile (S13 — display name is changeable anytime) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search users by display name or tag (S6) */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User profile card (S7) */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contact list */
        get: operations["listContacts"];
        put?: never;
        /**
         * Add contact (S7)
         * @description Creates a one-directional contact entry. When both users have added
         *     each other the relation becomes `mutual` — required for 1-1 chat
         *     creation and private-session invites.
         */
        post: operations["addContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove contact */
        delete: operations["removeContact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chat list (S4)
         * @description Ordered by last activity; includes 1-1 chats and groups.
         */
        get: operations["listChats"];
        put?: never;
        /** Open or create a 1-1 chat with a mutual contact (S7 → S5) */
        post: operations["openDirectChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat details (S5 header / S7 actions) */
        get: operations["getChat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin/unpin chat in own chat list (S4 ordering) */
        post: operations["setChatPinned"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Message history, cursor-paginated (S5) */
        get: operations["listMessages"];
        put?: never;
        /**
         * Send a message (S5)
         * @description Server assigns `id`, `seq`, `sentAt`. Delivery to online members
         *     happens via `message.new` WS event — see `docs/api/ws-events.md`.
         *     Optimistic-UI/outbox semantics are defined by the contract: client
         *     sends `clientNonce`; server echoes it in the response and the WS
         *     event for dedup. The pair `(senderId, clientNonce)` is unique:
         *     retrying a send with the same nonce returns the already-created
         *     message with `200` (never a duplicate), so outbox flush is safe.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a message
         * @description Own messages; in groups also users with `delete_messages` right.
         */
        delete: operations["deleteMessage"];
        options?: never;
        head?: never;
        /** Edit own message */
        patch: operations["editMessage"];
        trace?: never;
    };
    "/messages/{messageId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin/unpin a message (S5b pinned view)
         * @description Direct chats: either party. Groups: requires `pin_messages`
         *     right or owner.
         */
        post: operations["setMessagePinned"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an attachment (photo/file) */
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download an attachment blob
         * @description Authorized URL referenced by `Attachment.url`. Serving requires
         *     membership in the attachment's chat; non-members get 404 so the
         *     existence of an attachment is never revealed.
         */
        get: operations["downloadAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark chat read up to a message (read receipts) */
        post: operations["markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create group (S8) */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{chatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit group info (S9a, requires `edit_info`) */
        patch: operations["editGroup"];
        trace?: never;
    };
    "/groups/{chatId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add members (requires `invite_members` or owner) */
        post: operations["addGroupMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{chatId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove member (requires `remove_members` or owner; members can remove themselves) */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        /** Grant/revoke member rights (owner only, party/raid model) */
        patch: operations["setMemberRights"];
        trace?: never;
    };
    "/groups/{chatId}/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer ownership (owner only) */
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/vapid-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** VAPID public key for Web Push subscription (S15) */
        get: operations["getVapidKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a Web Push subscription for this device (S15)
         * @description Idempotent per `endpoint`: re-subscribing an existing endpoint
         *     updates keys and returns `200` with the existing id instead of
         *     creating a duplicate.
         */
        post: operations["createPushSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a Web Push subscription */
        delete: operations["deletePushSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a user to the instance owner (US-2.4) */
        post: operations["reportUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Error: {
            error: components["schemas"]["ErrorBody"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @description Free-form, changeable, NOT unique */
            displayName: string;
            /**
             * @description Immutable unique handle `name#NNNN`; `#1` reserved for instance owner
             * @example jojou#1042
             */
            tag: string;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceSession: {
            /** Format: uuid */
            id: string;
            deviceName: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            current: boolean;
        };
        Contact: {
            user: components["schemas"]["User"];
            /** @description Both parties added each other */
            mutual: boolean;
            /** Format: date-time */
            addedAt: string;
            /**
             * Format: date-time
             * @description Last identity verification of this contact (US-2.5/2.6).
             *     Written by the private layer; always null until the private
             *     module ships. Drives the optional freshness reminder.
             */
            verifiedAt?: string | null;
        };
        Chat: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "direct" | "group";
            /** @description Group title; null for direct chats */
            title?: string | null;
            peer?: components["schemas"]["User"];
            members?: components["schemas"]["GroupMember"][];
            /** Format: date-time */
            createdAt: string;
        };
        ChatSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "direct" | "group";
            title?: string | null;
            peer?: components["schemas"]["User"];
            lastMessage?: components["schemas"]["Message"];
            /** Format: date-time */
            lastActivityAt: string;
            /** @description Per-user, synced across the user's devices */
            unreadCount: number;
            /** @description Group chats only — for the "N members" row in S4 */
            memberCount?: number;
            /** @description User-side pin; pinned chats sort before unpinned, then by lastActivityAt desc */
            pinned?: boolean;
        };
        /** @description Party/raid model — owner grants specific rights per member */
        MemberRights: {
            /** @default false */
            inviteMembers: boolean;
            /** @default false */
            removeMembers: boolean;
            /** @default false */
            editInfo: boolean;
            /** @default false */
            pinMessages: boolean;
            /** @default false */
            deleteMessages: boolean;
        };
        GroupMember: {
            user: components["schemas"]["User"];
            /** @enum {string} */
            role: "owner" | "member";
            rights: components["schemas"]["MemberRights"];
            /** Format: date-time */
            joinedAt: string;
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "photo" | "file";
            mimeType: string;
            fileName?: string;
            sizeBytes: number;
            /** @description Authorized URL — requires the same bearer token, not a public link (server-trusted, not public internet) */
            url: string;
            thumbnailUrl?: string | null;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chatId: string;
            /** @description Per-chat monotonic sequence — ordering + read cursors */
            seq: number;
            /** Format: uuid */
            senderId: string;
            text?: string | null;
            attachments?: components["schemas"]["Attachment"][];
            /** Format: uuid */
            replyToMessageId?: string | null;
            /** @description Echoed for optimistic-UI dedup */
            clientNonce: string;
            /** Format: date-time */
            sentAt: string;
            /** Format: date-time */
            editedAt?: string | null;
            /** Format: date-time */
            deletedAt?: string | null;
            pinned?: boolean;
        };
    };
    responses: {
        /** @description Missing/expired token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "Token expired"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request failed validation */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit hit */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "rate_limited",
                 *         "message": "Too many requests"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        UserId: string;
        ChatId: string;
        MessageId: string;
        SessionId: string;
        AttachmentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        postgres?: "up" | "down";
                        /** @enum {string} */
                        redis?: "up" | "down";
                    };
                };
            };
            /** @description Service unhealthy — dependency down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "degraded";
                        /** @enum {string} */
                        postgres?: "up" | "down";
                        /** @enum {string} */
                        redis?: "up" | "down";
                    };
                };
            };
            /** @description Unexpected error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Required for first registration only. Returning users
                     *     re-login with email + OTP alone — the invite gates
                     *     account creation, not every sign-in. Omitting it for an
                     *     unknown email → `invite_required`. The invite is
                     *     consumed at successful `verifyOtp`, not at this step —
                     *     a failed OTP attempt does not burn it.
                     * @example GLS-9F2K-71
                     */
                    inviteCode?: string;
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description OTP sent */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 600 */
                        otpExpiresInS: number;
                        /** @example 60 */
                        resendAvailableInS: number;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            /**
             * @description `invite_required` — email unknown and no invite supplied;
             *     `invite_invalid` — invite supplied but wrong/consumed
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Resend cooldown active (`otp_cooldown`) */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "otp_cooldown",
                     *         "message": "Wait before requesting a new code",
                     *         "details": {
                     *           "resendAvailableInS": 42
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    code: string;
                    /** @example Pixel 8 — Chrome PWA */
                    deviceName: string;
                };
            };
        };
        responses: {
            /**
             * @description Verified. `needsProfile=true` for first login (client shows S3);
             *     `false` for returning users (client goes to S4).
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        needsProfile: boolean;
                        accessToken: string;
                        /** @example 900 */
                        accessTokenExpiresInS: number;
                        refreshToken: string;
                        /**
                         * @description `User` object, present only when `needsProfile=false`.
                         *     First login has no displayName/tag yet — profile is
                         *     created via `POST /auth/profile` (S3).
                         */
                        user?: Record<string, never> | null;
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            /** @description Code invalid or expired */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    completeProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example jojou */
                    displayName: string;
                    /** @description Optional explicit tag attempt (e.g. "Jojou13245" from suggestions) */
                    requestedTag?: string;
                };
            };
        };
        responses: {
            /** @description Profile created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            /** @description Tag taken — suggestions in `error.details.tagSuggestions` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        accessTokenExpiresInS: number;
                        refreshToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["DeviceSession"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user + private fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        /**
                         * Format: email
                         * @description Own login email — private, never exposed on the public `User` object or to other users
                         */
                        email: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string;
                    avatarUrl?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated profile. `tag` never changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                /** @description Display-name substring or exact `name#NNNN` tag */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: components["schemas"]["User"][];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                        /**
                         * Format: date-time
                         * @description Last identity verification of this contact (US-2.5
                         *     "verified" mark on the profile card). Always null
                         *     until the private module ships.
                         */
                        verifiedAt?: string | null;
                        /**
                         * @description none — strangers; contact_incoming — they added you,
                         *     you haven't (drives "add back?" prompt); contact_outgoing —
                         *     you added them; contact_mutual — both added; self.
                         * @enum {string}
                         */
                        relationship: "none" | "contact_incoming" | "contact_outgoing" | "contact_mutual" | "self";
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listContacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contacts: components["schemas"]["Contact"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contact: components["schemas"]["Contact"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Already in contacts */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chats: components["schemas"]["ChatSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    openDirectChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description Existing chat returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["Chat"];
                    };
                };
            };
            /** @description New chat created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["Chat"];
                    };
                };
            };
            /** @description Not mutual contacts */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["Chat"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setChatPinned: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pinned: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Opaque cursor from `nextCursor` of a previous page (older messages). Server implements it over the per-chat `seq`; clients must treat it as opaque. */
                before?: string;
                /** @description Opaque cursor from `newerCursor` — paginates toward newer messages (forward scroll after an `around` jump). */
                after?: string;
                limit?: number;
                /** @description Full-text search within this chat (S5b). When set, results are matching messages ordered by seq desc; `before` cursor paginates further matches. */
                q?: string;
                /** @description When true, returns only pinned messages (S5b pinned view) */
                pinned?: boolean;
                /**
                 * @description Jump-to-message (search results, pinned messages, replies):
                 *     returns a window of `limit` messages centered on this message's
                 *     seq. Mutually exclusive with `q` and `pinned`.
                 */
                around?: string;
            };
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages: components["schemas"]["Message"][];
                        /** @description Cursor toward older messages; null at history start */
                        nextCursor: string | null;
                        /**
                         * @description Cursor toward newer messages — only non-null after an
                         *     `around` jump, letting the client scroll forward from
                         *     the jumped position; pass it in the `after` param.
                         *     null when already at the latest.
                         */
                        newerCursor: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Client-generated idempotency key (uuid) */
                    clientNonce: string;
                    /** @description Required unless `attachmentIds` is non-empty */
                    text?: string;
                    /**
                     * @description Required unless `text` is non-empty. Each id must
                     *     reference an attachment uploaded to this chat
                     *     (`POST /chats/{chatId}/attachments`), else
                     *     `validation_failed`.
                     */
                    attachmentIds?: string[];
                    /**
                     * Format: uuid
                     * @description Must reference a message in this chat
                     */
                    replyToMessageId?: string;
                };
            };
        };
        responses: {
            /** @description Idempotent replay — `clientNonce` was already used, returns the existing message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: components["schemas"]["Message"];
                    };
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: components["schemas"]["Message"];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    editMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: components["schemas"]["Message"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setMessagePinned: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageId: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pinned: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: components["schemas"]["Message"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        attachment: components["schemas"]["Attachment"];
                    };
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    downloadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The blob */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    upToSeq: number;
                };
            };
        };
        responses: {
            /** @description Recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    memberIds: string[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["Chat"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    editGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["Chat"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    addGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    memberIds: string[];
                };
            };
        };
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    setMemberRights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rights: components["schemas"]["MemberRights"];
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        member: components["schemas"]["GroupMember"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: components["parameters"]["ChatId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    newOwnerId: string;
                };
            };
        };
        responses: {
            /** @description Transferred */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getVapidKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VAPID public key (applicationServerKey) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        publicKey: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    endpoint: string;
                    keys: {
                        p256dh: string;
                        auth: string;
                    };
                };
            };
        };
        responses: {
            /** @description Existing subscription updated (same endpoint) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                    };
                };
            };
            /** @description Subscription stored (bound to the current device session) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deletePushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reportUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    userId: string;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Report accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
